on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:  # hier kannst du dann manuell triggern!

jobs:
  rpm:
    uses: lbetz/ci-workflows/.github/workflows/rpm-build.yml@rework
    with:
      ci_workflows_ref: "rework"
      distros: '["fedora44", "el9"]'
      architectures: '["x86_64"]'
